# Numpy

### 1. 기본적인것들

In [1]:
import numpy as np

In [2]:
data = [[1,2,3,], [4,5,6], [7,8,9]]

a= np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a.dtype

dtype('int32')

In [4]:
type(a)

numpy.ndarray

In [5]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [5]:
#형 변환
a =a.astype(np.float32) #or u can do it like -> a= a.astype('float32')
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [11]:
#접근
a[2][0] # == a[2,0]

7.0

In [10]:
a[0]

array([1., 2., 3.], dtype=float32)

In [15]:
np.arange(1,10,2) # arange(start,stop,step) / range와 같다.

array([1, 3, 5, 7, 9])

In [19]:
np.arange(1,11).reshape(5,2) # reshape으로 matrix 형태로 변환 가능. 5행2열

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
t1 = np.arange(1,13).reshape(2,3,2) #  reshape(행, 열, depth)
t1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [18]:
t1.ndim

4

In [22]:
np.nan + 1 #nan 값은 평균을 구할 때 잡히지 않는다. + int형에서는 사용 불가, float에서만 사용 가능

nan

In [26]:
a[0][1] = np.nan
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [31]:
b = np.arange(1,10).reshape(3,3)
b.dtype

dtype('int32')

In [28]:
b[0][1] = np.nan # int형에는 nan 사용 x

ValueError: cannot convert float NaN to integer

In [33]:
a = np.linspace(1,10,20) # linspace(시작,종료,몇개 생성)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### 2. 연산

In [39]:
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
data + data #일반적인 python에서는 되지 않는다.

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [46]:
data - data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [44]:
data * data #그러나 원소들끼리의 곱셈과 나눗셈이지 행렬의 연산은 아니다!

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [49]:
data / data#그러나 원소들끼리의 곱셈과 나눗셈이지 행렬의 연산은 아니다!

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 3. 행렬 연산

In [48]:
np.dot(data,data) # dot 연산. 즉, 곱셈

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [51]:
data@data # dot 연산임. 이것도 사용 가능.

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### 4. 차원 array, scalar

In [52]:
#0차원 : 스칼라 scalar
a = np.array(1)
a

array(1)

In [54]:
a.shape # 0차원이기 때문에 shape 없다고 나옴.

()

In [55]:
a.ndim # dimension 차원 은 0

0

In [59]:
#1차원 : vector
a = np.array([1])
a
#a.shape
#a.ndim

array([1])

In [64]:
#2차원 : Matrix
a = np.array([[1,2,3],[4,5,6]])
a
a.shape # (2,3) -> 2행 3열 
a.ndim # 2 -> 2차원

2

In [69]:
# 3차원 : 3차원 이상의 다차원 행렬을 Tensor라고 부른다.
a = np.array([ [[1,2,3,],[4,5,6]],[[2,4,5],[3,3,3] ]])
a
a.shape
#a.ndim

(2, 2, 3)

### 5. matrix 유형

In [71]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [73]:
b = np.ones(12).reshape(2,3,2)
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [86]:
c = np.zeros(12).reshape(2,3,2) # == np.zeros([2,3,2]) 같은 결과나옴.
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [80]:
d = np.eye(3) # 단위행렬 = I
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
e = np.zeros([3,4]) # 0으로 체움
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
f = np.zeros([2,3,2]) #
f

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [88]:
f = np.empty([2,3]) # '0에 가까운 값이 존재하는 숫자'로 체움.
f

array([[4.24399158e-314, 8.48798317e-314, 1.27319747e-313],
       [8.48798316e-314, 6.36598738e-314, 6.36598737e-314]])

In [95]:
g = np.full((3,4),100) # ((3,4),100) => 3행 4열을 100으로 체워라
g

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [97]:
g = np.full(3,4) # (3,4) => 3열을 4로 체워라, 행은 defult = 1로 체움.
g
#g.ndim

array([4, 4, 4])

In [99]:
h = np.linspace(2,10,6) #start 2 , stop 10, step 6
h # 2 ~ 10을 동등한 간격으로 6개로 쪼갠다.

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

### 6. 집계 함수

In [121]:
a = np.arange(0,10).reshape(2,5)
a[0][0] = 50
a

array([[50,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [122]:
np.mean(a)

9.5

In [124]:
np.median(a) # 중앙값. 단, 짝수 ...?? 왜 4.5가 아니라 5.5지?

5.5

In [125]:
np.std(a) # 표준편차

13.720422734012244

In [127]:
np.var(a) # 분산

188.25

In [128]:
np.sum(a) # 숫자 전부다 더한 값.

95

In [130]:
sum(a) # column으로 더한 값.

array([55,  7,  9, 11, 13])

In [131]:
np.sum(a, axis=0) # axis = 0이면 column으로 더한다.

array([55,  7,  9, 11, 13])

In [134]:
np.sum(a, axis=1) # axis = 0이면 row으로 더한다.

array([60, 35])

In [136]:
np.max(a)

50

In [139]:
np.max(a, axis = 0) # column에서 각자 max 값 출력

array([50,  6,  7,  8,  9])

In [140]:
np.min(a, axis = 1)

array([1, 5])