# Numpy 기초 연습문제

In [46]:
import numpy as np

## 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [47]:
a = np.zeros([3,4]) # np.zeros([2,2]) OR np.zeros((2,2)) 둘 다 가능
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

```python
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])
```

In [48]:
a.shape # a array의 형태

(3, 4)

In [49]:
for i in range(a.shape[0]): # 행
    for j in range(a.shape[1]): #열
        a[i ,j] = i*4 + j + 1 
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [50]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

## 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [51]:
a[1, 2]

7.0

## 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

```python
array([[5., 6., 7., 8.]])

```

In [52]:
a[[1],:]

array([[5., 6., 7., 8.]])

## 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

```python
array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])
```

In [53]:
a[:,[1,2]]

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

## 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

```python
array([1., 2., 3., 4., 5., 6.])
```

In [54]:
a.shape # shape 확인.

(3, 4)

In [55]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

In [56]:
a[a <= 6]

array([1., 2., 3., 4., 5., 6.])

In [57]:
a[a < 7]

array([1., 2., 3., 4., 5., 6.])

## 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [58]:
b = np.random.random([3, 4]) # np.random.random((3, 4)) 도 같은 결과.
b

array([[0.8645994 , 0.29484853, 0.49000922, 0.99070924],
       [0.03528594, 0.32573328, 0.07561146, 0.59162389],
       [0.40993696, 0.58630545, 0.98649188, 0.01214882]])

## 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [59]:
c = a * b
c

array([[ 0.8645994 ,  0.58969705,  1.47002767,  3.96283695],
       [ 0.1764297 ,  1.95439969,  0.52928019,  4.73299116],
       [ 3.68943267,  5.86305446, 10.85141063,  0.14578588]])

## 9. b의 전치행렬을 구하여 d에 저장하시오.

In [60]:
d = b.T # Transpose => 행과 열을 뒤집는다고 생각해도 된다.
d

array([[0.8645994 , 0.03528594, 0.40993696],
       [0.29484853, 0.32573328, 0.58630545],
       [0.49000922, 0.07561146, 0.98649188],
       [0.99070924, 0.59162389, 0.01214882]])

In [61]:
#b와 c(=b의 transpose) shape 비교.

print('b의 shape :',b.shape)
print('d의 shape :',d.shape)

b의 shape : (3, 4)
d의 shape : (4, 3)


## 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [62]:
print(a.shape, d.shape)

(3, 4) (4, 3)


## 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [63]:
e = a.dot(d) # 내적
e

array([[ 6.88716108,  3.28008245,  4.59061878],
       [17.44782664,  7.39310075, 12.57015121],
       [28.00849221, 11.50611904, 20.54968364]])

In [64]:
e.shape # (3,4)와 (4,3)의 내적은 (3,3).

(3, 3)

## 12. e에 대하여 각 열의 합을 계산하시오.

In [65]:
np.sum(e, axis=1) # axis =1  열

array([14.75786231, 37.4110786 , 60.06429489])

In [66]:
np.sum(e, axis=0) # row sum

array([52.34347993, 22.17930224, 37.71045363])